services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=subscriptionsdb'
      - 'POSTGRES_PASSWORD=usersub'
      - 'POSTGRES_USER=BrainDias'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "BrainDias", "-d", "subscriptionsdb" ]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
